var weapon_list = [
 {
   "Label": "Gauntlet",
   "Cost": "2 gp",
   "Dmg_(S)": "1d2",
   "Dmg_(M)": "1d3",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si1_",
   "Type3": "unarmed",
   "Type4": "melee"
 },
 {
   "Label": "Unarmed strike",
   "Cost": "0",
   "Dmg_(S)": "1d2",
   "Dmg_(M)": "1d3",
   "Critical": "x2",
   "Range": "",
   "Weight1": "0",
   "Type2": "B",
   "Special": "nonlethal",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si2_",
   "Type3": "unarmed",
   "Type4": "melee"
 },
 {
   "Label": "Battle aspergillum",
   "Cost": "5 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "4 lb.",
   "Type2": "B",
   "Special": "see text",
   "Source": "PRG:APG",
   "Type": "si_",
   "Type5": "si3_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Brass knife",
   "Cost": "2 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "10 ft.",
   "Weight1": "1 lb.",
   "Type2": "P or S",
   "Special": "fragile",
   "Source": "PPC:Pirates",
   "Type": "si_",
   "Type5": "si4_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Brass knuckles",
   "Cost": "1 gp",
   "Dmg_(S)": "1d2",
   "Dmg_(M)": "1d3",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "monk",
   "Source": "PPC:AA/PRG:APG",
   "Type": "si_",
   "Type5": "si5_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Cestus",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "B or P",
   "Special": "monk",
   "Source": "PRG:APG",
   "Type": "si_",
   "Type5": "si6_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Dagger",
   "Cost": "2 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "10 ft.",
   "Weight1": "1 lb.",
   "Type2": "P or S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si7_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Dagger, punching",
   "Cost": "2 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x3",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si8_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Gauntlet, spiked",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si9_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Hook hand",
   "Cost": "10 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "disarm",
   "Source": "PPC:Pirates",
   "Type": "si_",
   "Type5": "si10_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kunai",
   "Cost": "2 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "2 lbs.",
   "Type2": "B or P",
   "Special": "",
   "Source": "PPC:RTT",
   "Type": "si_",
   "Type5": "si11_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Mace, light",
   "Cost": "5 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si12_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Sickle",
   "Cost": "6 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "trip",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si13_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Spring blade",
   "Cost": "70 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "1 lb.",
   "Type2": "P or S",
   "Special": "",
   "Source": "PRG:UI",
   "Type": "si_",
   "Type5": "si14_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Wooden stake",
   "Cost": "",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:APG",
   "Type": "si_",
   "Type5": "si15_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Club",
   "Cost": "",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "3 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si16_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Club, mere",
   "Cost": "2 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "B or P",
   "Special": "fragile",
   "Source": "PPC:AA",
   "Type": "si_",
   "Type5": "si17_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Mace, heavy",
   "Cost": "12 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "8 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si18_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Morningstar",
   "Cost": "8 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "6 lbs.",
   "Type2": "B and P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si19_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Shortspear",
   "Cost": "1 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si20_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Bayonet",
   "Cost": "5 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:APG",
   "Type": "si_",
   "Type5": "si21_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Boarding pike",
   "Cost": "8 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "9 lbs.",
   "Type2": "P",
   "Special": "brace, reach",
   "Source": "PPC:Pirates",
   "Type": "si_",
   "Type5": "si22_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Kumade",
   "Cost": "5 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "grapple",
   "Source": "PPC:MTT",
   "Type": "si_",
   "Type5": "si23_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Kumade, collapsible",
   "Cost": "10 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "grapple",
   "Source": "PPC:MTT",
   "Type": "si_",
   "Type5": "si24_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Longspear",
   "Cost": "5 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "9 lbs.",
   "Type2": "P",
   "Special": "brace, reach",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si25_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Quarterstaff",
   "Cost": "",
   "Dmg_(S)": "1d4/1d4",
   "Dmg_(M)": "1d6/1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "B",
   "Special": "double, monk",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si26_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Spear",
   "Cost": "2 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "20 ft.",
   "Weight1": "6 lbs.",
   "Type2": "P",
   "Special": "brace",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si27_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Spear, boar",
   "Cost": "5 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "8 lb.",
   "Type2": "P",
   "Special": "brace, see text",
   "Source": "PRG:APG",
   "Type": "si_",
   "Type5": "si28_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Spear, weighted",
   "Cost": "10 gp",
   "Dmg_(S)": "1d6/1d4",
   "Dmg_(M)": "1d8/1d6",
   "Critical": "x3/x2",
   "Range": "",
   "Weight1": "8 lbs.",
   "Type2": "B or P",
   "Special": "brace, double",
   "Source": "PPC:MTT",
   "Type": "si_",
   "Type5": "si29_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Blowgun",
   "Cost": "2 gp",
   "Dmg_(S)": "1",
   "Dmg_(M)": "1d2",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si30_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, heavy",
   "Cost": "50 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "120 ft.",
   "Weight1": "8 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si31_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, heavy (underwater)",
   "Cost": "100 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "120 ft.",
   "Weight1": "8 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "si_",
   "Type5": "si32_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, light",
   "Cost": "35 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "80 ft.",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si33_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, light (underwater)",
   "Cost": "70 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "80 ft.",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "si_",
   "Type5": "si34_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Dart",
   "Cost": "5 sp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "1/2 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si35_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Javelin",
   "Cost": "1 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "30 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si36_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Sling",
   "Cost": "",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "50 ft.",
   "Weight1": "",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "si_",
   "Type5": "si37_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Stingchuck",
   "Cost": "",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "9 lbs.",
   "Type2": "B",
   "Special": "see text",
   "Source": "PPC:AA",
   "Type": "si_",
   "Type5": "si38_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Stonebow",
   "Cost": "35 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "50 ft.",
   "Weight1": "4 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PPC:RTT",
   "Type": "si_",
   "Type5": "si39_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Axe, boarding",
   "Cost": "6 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "",
   "Weight1": "3 lbs.",
   "Type2": "P or S",
   "Special": "",
   "Source": "PPC:Pirates",
   "Type": "ma_",
   "Type5": "ma1_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Axe, throwing",
   "Cost": "8 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma2_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Blade boot",
   "Cost": "25 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "see text",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma3_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Cat-o�-nine-tails",
   "Cost": "1 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "disarm, nonlethal",
   "Source": "PPC:Pirates",
   "Type": "ma_",
   "Type5": "ma4_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Dogslicer",
   "Cost": "8 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "fragile",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma5_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Hammer, light",
   "Cost": "1 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma6_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Gladius",
   "Cost": "15 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "3 lbs.",
   "Type2": "P or S",
   "Special": "performance",
   "Source": "PRG:UC",
   "Type": "ma_",
   "Type5": "ma7_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Handaxe",
   "Cost": "6 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "",
   "Weight1": "3 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma8_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Knife, switchblade",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "10 ft.",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma9_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kobold tail attachment, Long lash",
   "Cost": "15 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "reach",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma10_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kobold tail attachment, Pounder",
   "Cost": "1 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma11_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kobold tail attachment, Razored",
   "Cost": "3 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma12_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kobold tail attachment, Spiked",
   "Cost": "3 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma13_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kobold tail attachment, Sweeper",
   "Cost": "7 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "3 lbs.",
   "Type2": "B",
   "Special": "trip",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma14_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kukri",
   "Cost": "8 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "18-20/x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma15_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Machete",
   "Cost": "10 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PPC:MTT",
   "Type": "ma_",
   "Type5": "ma16_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Pick, light",
   "Cost": "4 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x4",
   "Range": "",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma17_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Ratfolk tailblade",
   "Cost": "11 gp",
   "Dmg_(S)": "1d2",
   "Dmg_(M)": "1d3",
   "Critical": "20/x2",
   "Range": "",
   "Weight1": "1/2 lb.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma18_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Sap",
   "Cost": "1 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "nonlethal",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma19_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Sea-knife",
   "Cost": "8 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma20_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Shield, light",
   "Cost": "3 gp/9 gp",
   "Dmg_(S)": "1d2",
   "Dmg_(M)": "1d3",
   "Critical": "x2",
   "Range": "",
   "Weight1": "special",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma21_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Spiked armor",
   "Cost": "special",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "special",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma22_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Spiked shield, light",
   "Cost": "13 gp/ 19 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "special",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma23_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Starknife",
   "Cost": "24 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x3",
   "Range": "20 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma24_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Sword, short",
   "Cost": "10 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma25_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "War razor",
   "Cost": "8 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "",
   "Source": "PCS:ISWG-Revised",
   "Type": "ma_",
   "Type5": "ma26_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Ankus",
   "Cost": "8 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "5 lbs.",
   "Type2": "P",
   "Special": "disarm, trip",
   "Source": "PPC:MTT",
   "Type": "ma_",
   "Type5": "ma27_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Battleaxe",
   "Cost": "10 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "6 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma28_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Combat scabbard",
   "Cost": "1 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "improvised, see text",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma29_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Cutlass",
   "Cost": "15 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "18-20/x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PPC:Pirates",
   "Type": "ma_",
   "Type5": "ma30_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flail",
   "Cost": "8 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "5 lbs.",
   "Type2": "B",
   "Special": "disarm, trip",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma31_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Gandasa",
   "Cost": "15 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "2d4",
   "Critical": "x3",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PPC:MTT",
   "Type": "ma_",
   "Type5": "ma32_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Klar",
   "Cost": "12 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "6 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PCS:ISWG-Revised",
   "Type": "ma_",
   "Type5": "ma33_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Longsword",
   "Cost": "15 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma34_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Manople",
   "Cost": "17 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "P or S",
   "Special": "blocking, disarm",
   "Source": "PPC:MTT",
   "Type": "ma_",
   "Type5": "ma35_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Pick, heavy",
   "Cost": "8 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x4",
   "Range": "",
   "Weight1": "6 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma36_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Rapier",
   "Cost": "20 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "18-20/x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma37_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Scabbard, combat (sharpened)",
   "Cost": "10 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "see text",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma38_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Scimitar",
   "Cost": "15 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "18-20/x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma39_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Scizore",
   "Cost": "20 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x2",
   "Range": "",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:UC",
   "Type": "ma_",
   "Type5": "ma40_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Shield, heavy",
   "Cost": "special",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "special",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma41_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Spiked shield, heavy",
   "Cost": "17 gp/30 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "special",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma42_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Sword cane",
   "Cost": "45 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma43_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Terbutje",
   "Cost": "5 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "fragile",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma44_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Terbutje, steel",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "4 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma45_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Trident",
   "Cost": "15 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "brace",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma46_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Warhammer",
   "Cost": "12 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "5 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma47_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Bardiche",
   "Cost": "13 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "14 lbs.",
   "Type2": "S",
   "Special": "brace, reach, see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma48_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Bec de corbin",
   "Cost": "15 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "B or P",
   "Special": "brace, reach, see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma49_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Bill",
   "Cost": "11 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "11 lbs.",
   "Type2": "S",
   "Special": "brace, disarm, reach, see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma50_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Earth breaker",
   "Cost": "40 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "2d6",
   "Critical": "x3",
   "Range": "",
   "Weight1": "14 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PCS:ISWG-Revised",
   "Type": "ma_",
   "Type5": "ma51_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Falchion",
   "Cost": "75 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "2d4",
   "Critical": "18-20/x2",
   "Range": "",
   "Weight1": "8 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma52_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flail, heavy",
   "Cost": "15 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "B",
   "Special": "disarm, trip",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma53_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Glaive",
   "Cost": "8 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "S",
   "Special": "reach",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma54_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Glaive-guisarme",
   "Cost": "12 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "S",
   "Special": "brace, reach, see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma55_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Greataxe",
   "Cost": "20 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "1d12",
   "Critical": "x3",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma56_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Greatclub",
   "Cost": "5 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x2",
   "Range": "",
   "Weight1": "8 lbs.",
   "Type2": "B",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma57_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Greatsword",
   "Cost": "50 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "2d6",
   "Critical": "19-20/x2",
   "Range": "",
   "Weight1": "8 lbs.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma58_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Guisarme",
   "Cost": "9 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "2d4",
   "Critical": "x3",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "S",
   "Special": "reach, trip",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma59_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Halberd",
   "Cost": "10 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "P or S",
   "Special": "brace, trip",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma60_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Hammer, lucerne",
   "Cost": "15 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "1d12",
   "Critical": "x2",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "B or P",
   "Special": "brace, reach, see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma61_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Horsechopper",
   "Cost": "10 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "P or S",
   "Special": "reach, trip",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma62_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Lance",
   "Cost": "10 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "P",
   "Special": "reach",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma63_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Ogre hook",
   "Cost": "24 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "P",
   "Special": "trip",
   "Source": "PCS:ISWG-Revised",
   "Type": "ma_",
   "Type5": "ma64_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Pickaxe",
   "Cost": "14 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x4",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PAP14",
   "Type": "ma_",
   "Type5": "ma65_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Planson",
   "Cost": "10 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x2",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "B or P",
   "Special": "brace",
   "Source": "PPC:MTT",
   "Type": "ma_",
   "Type5": "ma66_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Ranseur",
   "Cost": "10 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "2d4",
   "Critical": "x3",
   "Range": "",
   "Weight1": "12 lbs.",
   "Type2": "P",
   "Special": "disarm, reach",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma67_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Scythe",
   "Cost": "18 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "2d4",
   "Critical": "x4",
   "Range": "",
   "Weight1": "10 lbs.",
   "Type2": "P or S",
   "Special": "trip",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma68_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Spear, syringe",
   "Cost": "100 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "20 ft.",
   "Weight1": "6 lbs.",
   "Type2": "P",
   "Special": "brace, see text",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma69_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Ammentum",
   "Cost": "",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "50 ft.",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "performance",
   "Source": "PRG:UC",
   "Type": "ma_",
   "Type5": "ma70_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Chakram",
   "Cost": "1 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "30 ft.",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma71_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Dart, jolting",
   "Cost": "100 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "1/2 lb.",
   "Type2": "P",
   "Special": "see text",
   "Source": "PRG:ARG",
   "Type": "ma_",
   "Type5": "ma72_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Hunga munga",
   "Cost": "4 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "15 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PPC:AA",
   "Type": "ma_",
   "Type5": "ma73_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Hurlbat",
   "Cost": "8 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "10 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P and S",
   "Special": "",
   "Source": "PPC:RTT",
   "Type": "ma_",
   "Type5": "ma74_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow",
   "Cost": "75 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "100 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma75_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow, composite (+0)",
   "Cost": "100 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "110 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "Strength (-)",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma76_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow, composite (+1)",
   "Cost": "200 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "110 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "Strength (12)",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma77_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow, composite (+2)",
   "Cost": "300 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "110 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "Strength (14)",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma78_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow, composite (+3)",
   "Cost": "400 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "110 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "Strength (16)",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma79_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow, composite (+4)",
   "Cost": "500 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "110 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "Strength (18)",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma80_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Longbow, composite (+5)",
   "Cost": "600 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "110 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "Strength (20)",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma81_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Pilum",
   "Cost": "5 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "see text",
   "Source": "PRG:APG",
   "Type": "ma_",
   "Type5": "ma82_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Shortbow",
   "Cost": "30 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "60 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma83_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Shortbow, composite",
   "Cost": "75 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "70 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "",
   "Source": "PRG:CRB",
   "Type": "ma_",
   "Type5": "ma84_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Spear-sling",
   "Cost": "50 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "see text",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "see text",
   "Source": "PPC:RTT",
   "Type": "ma_",
   "Type5": "ma85_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Throwing arrow cord",
   "Cost": "",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "60 ft.",
   "Weight1": "",
   "Type2": "P",
   "Special": "",
   "Source": "PPC:RTT",
   "Type": "ma_",
   "Type5": "ma86_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Aklys",
   "Cost": "5 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "performance, trip",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex1_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Axe, knuckle",
   "Cost": "9 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "monk, performance",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex2_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Barbazu beard",
   "Cost": "25 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "5 lbs",
   "Type2": "S",
   "Special": "see text",
   "Source": "PPC:Devils",
   "Type": "ex_",
   "Type5": "ex3_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Battle poi",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3 fire",
   "Dmg_(M)": "1d4 fire",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "fire",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex4_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Dagger, swordbreaker",
   "Cost": "10 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "3 lbs.",
   "Type2": "S",
   "Special": "disarm, sunder",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex5_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Flying Talon",
   "Cost": "15 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "5 lbs.",
   "Type2": "P",
   "Special": "disarm, trip",
   "Source": "ModuleD1",
   "Type": "ex_",
   "Type5": "ex6_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Gnome pincher",
   "Cost": "10 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "disarm, see text",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex7_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Halfling rope-shot",
   "Cost": "1 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "disarm",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex8_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Helmet, dwarven boulder",
   "Cost": "20 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "B",
   "Special": "see text",
   "Source": "PRG:ARG",
   "Type": "ex_",
   "Type5": "ex9_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Kama",
   "Cost": "2 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "monk, trip",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex10_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Katar, tri-bladed",
   "Cost": "6 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x4",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PCS",
   "Type": "ex_",
   "Type5": "ex11_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Knife, butterfly",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "1 lb.",
   "Type2": "P or S",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex12_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Knife, deer horn",
   "Cost": "10 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x3",
   "Range": "20 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "blocking, monk",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex13_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Maulaxe, dwarven",
   "Cost": "25 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "10 ft.",
   "Weight1": "5 lbs.",
   "Type2": "B or S",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex14_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Nunchaku",
   "Cost": "2 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "disarm, monk",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex15_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Quadrens",
   "Cost": "8 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "performance",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex16_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Rope gauntlet",
   "Cost": "2 sp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "B (or S)",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex17_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Sai",
   "Cost": "1 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "disarm, monk",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex18_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Siangham",
   "Cost": "3 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "monk",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex19_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Sica",
   "Cost": "10 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "performance",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex20_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Thorn bracer",
   "Cost": "30 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PCS",
   "Type": "ex_",
   "Type5": "ex21_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Whip, scorpion",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "3 lbs.",
   "Type2": "S",
   "Special": "disarm, performance, reach, trip",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex22_",
   "Type3": "light",
   "Type4": "melee"
 },
 {
   "Label": "Axe, hooked",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "7 lbs.",
   "Type2": "S",
   "Special": "disarm, performance, trip",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex23_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Estoc",
   "Cost": "50 gp",
   "Dmg_(S)": "2d3",
   "Dmg_(M)": "2d4",
   "Critical": "18-20/x2",
   "Range": "-",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex24_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Falcata",
   "Cost": "18 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x3",
   "Range": "-",
   "Weight1": "4 lbs.",
   "Type2": "S",
   "Special": "-",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex25_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flindbar",
   "Cost": "9 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "6 lbs.",
   "Type2": "B and P",
   "Special": "disarm, trip",
   "Source": "MC",
   "Type": "ex_",
   "Type5": "ex26_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Khopesh",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "8 lbs.",
   "Type2": "S",
   "Special": "trip",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex27_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Knobkerrie",
   "Cost": "5 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "4 lbs.",
   "Type2": "B",
   "Special": "see text",
   "Source": "PPC:RTT",
   "Type": "ex_",
   "Type5": "ex28_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Rhoka",
   "Cost": "5 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "18-20/x2",
   "Range": "-",
   "Weight1": "6 lbs.",
   "Type2": "S",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex29_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Sabre, sawtooth",
   "Cost": "35 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "-",
   "Source": "PCS:ISWG-Revised",
   "Type": "ex_",
   "Type5": "ex30_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Shotel",
   "Cost": "30 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "performance",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex31_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Sword, dueling",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "3 lbs",
   "Type2": "S",
   "Special": "-",
   "Source": "PCS:ISWG-Revised",
   "Type": "ex_",
   "Type5": "ex32_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Sword, bastard",
   "Cost": "35 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "6 lbs.",
   "Type2": "S",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex33_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Tongi",
   "Cost": "18 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "19-20/x3",
   "Range": "-",
   "Weight1": "4 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex34_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Waraxe, dwarven",
   "Cost": "30 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "8 lbs.",
   "Type2": "S",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex35_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Waraxe, dwarven double",
   "Cost": "60 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "12 lbs.",
   "Type2": "S",
   "Special": "see text",
   "Source": "PRG:ARG",
   "Type": "ex_",
   "Type5": "ex36_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Whip",
   "Cost": "1 gp",
   "Dmg_(S)": "1d2",
   "Dmg_(M)": "1d3",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "disarm, nonlethal, reach, trip",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex37_",
   "Type3": "one_handed",
   "Type4": "melee"
 },
 {
   "Label": "Axe, Orc Double",
   "Cost": "60 gp",
   "Dmg_(S)": "1d6/1d6",
   "Dmg_(M)": "1d8/1d8",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "15 lbs.",
   "Type2": "S",
   "Special": "double",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex38_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Battle Ladder",
   "Cost": "20 gp",
   "Dmg_(S)": "1d4/1d4",
   "Dmg_(M)": "1d6/1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "8 lbs.",
   "Type2": "B",
   "Special": "trip",
   "Source": "PPC:Goblins",
   "Type": "ex_",
   "Type5": "ex39_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Boarding gaff",
   "Cost": "8 gp",
   "Dmg_(S)": "1d4/1d4",
   "Dmg_(M)": "1d6/1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "8 lbs.",
   "Type2": "S",
   "Special": "double, reach, trip",
   "Source": "PPC:Pirates",
   "Type": "ex_",
   "Type5": "ex40_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Chain, Spiked",
   "Cost": "25 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "2d4",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "P",
   "Special": "disarm, trip",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex41_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Crook",
   "Cost": "1 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "5 lbs.",
   "Type2": "B",
   "Special": "reach, trip",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex42_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Curve blade, elven",
   "Cost": "80 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "18-20/x2",
   "Range": "-",
   "Weight1": "7 lbs.",
   "Type2": "S",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex43_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Dorn Dergar, dwarven",
   "Cost": "50 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "15 lbs.",
   "Type2": "B",
   "Special": "reach",
   "Source": "PPC:Dwarves",
   "Type": "ex_",
   "Type5": "ex44_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Elven branched spear",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "P",
   "Special": "brace, reach",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex45_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Fauchard",
   "Cost": "14 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "18-20/x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "S",
   "Special": "reach, trip",
   "Source": "PCh:CHR",
   "Type": "ex_",
   "Type5": "ex46_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flail, dire",
   "Cost": "90 gp",
   "Dmg_(S)": "1d6/1d6",
   "Dmg_(M)": "1d8/1d8",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "B",
   "Special": "disarm, double, trip",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex47_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flailpole",
   "Cost": "15 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "S",
   "Special": "reach, trip",
   "Source": "PPC:Goblins",
   "Type": "ex_",
   "Type5": "ex48_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flambard",
   "Cost": "50 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "6 lbs.",
   "Type2": "S",
   "Special": "sunder",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex49_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Flying blade",
   "Cost": "40 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "1d12",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "12 lbs.",
   "Type2": "S",
   "Special": "performance, reach",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex50_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Garrote",
   "Cost": "3 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "1 lb.",
   "Type2": "S",
   "Special": "grapple, see text",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex51_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Hammer, Gnome hooked",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6/1d4",
   "Dmg_(M)": "1d8/1d6",
   "Critical": "x3/x4",
   "Range": "-",
   "Weight1": "6 lbs.",
   "Type2": "B or P",
   "Special": "double, trip",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex52_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Harpoon",
   "Cost": "5 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "10 ft.",
   "Weight1": "16 lbs.",
   "Type2": "P",
   "Special": "grapple",
   "Source": "PPC:Pirates",
   "Type": "ex_",
   "Type5": "ex53_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Longaxe, dwarven",
   "Cost": "50 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "1d12",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "14 lbs.",
   "Type2": "S",
   "Special": "reach",
   "Source": "PRG:ARG",
   "Type": "ex_",
   "Type5": "ex54_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Longhammer, dwarven",
   "Cost": "70 gp",
   "Dmg_(S)": "1d10",
   "Dmg_(M)": "2d6",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "20 lbs.",
   "Type2": "B",
   "Special": "reach",
   "Source": "PRG:ARG",
   "Type": "ex_",
   "Type5": "ex55_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Mancatcher",
   "Cost": "15 gp",
   "Dmg_(S)": "1",
   "Dmg_(M)": "1d2",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "P",
   "Special": "grapple, reach, see text",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex56_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Orc skull ram",
   "Cost": "15 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "20 lbs.",
   "Type2": "B",
   "Special": "reach",
   "Source": "PPC:MTT",
   "Type": "ex_",
   "Type5": "ex57_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Piston maul",
   "Cost": "70 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "15 lbs.",
   "Type2": "B",
   "Special": "see text",
   "Source": "PPC:Goblins",
   "Type": "ex_",
   "Type5": "ex58_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Ripsaw glaive",
   "Cost": "30 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "12 lbs.",
   "Type2": "S",
   "Special": "reach, see text",
   "Source": "PPC:Goblins",
   "Type": "ex_",
   "Type5": "ex59_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Scarf, bladed",
   "Cost": "12 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "2 lbs.",
   "Type2": "S",
   "Special": "disarm, trip",
   "Source": "PCS:ISWG-Revised",
   "Type": "ex_",
   "Type5": "ex60_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Spear, totem",
   "Cost": "25 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "x3",
   "Range": "10 ft.",
   "Weight1": "6 lbs.",
   "Type2": "P or S",
   "Special": "see text",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex61_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Sword, two-bladed",
   "Cost": "100 gp",
   "Dmg_(S)": "1d6/1d6",
   "Dmg_(M)": "1d8/1d8",
   "Critical": "19-20/x2",
   "Range": "-",
   "Weight1": "10 lbs.",
   "Type2": "S",
   "Special": "double",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex62_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Urgrosh, dwarven",
   "Cost": "50 gp",
   "Dmg_(S)": "1d6/1d4",
   "Dmg_(M)": "1d8/1d6",
   "Critical": "x3",
   "Range": "-",
   "Weight1": "12 lbs.",
   "Type2": "P or S",
   "Special": "brace, double",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex63_",
   "Type3": "two_handed",
   "Type4": "melee"
 },
 {
   "Label": "Darts, featherweight (10)",
   "Cost": "1 gp",
   "Dmg_(S)": "-",
   "Dmg_(M)": "-",
   "Critical": "-",
   "Range": "-",
   "Weight1": "-",
   "Type2": "-",
   "Special": "-",
   "Source": "PRG:UI",
   "Type": "ex_",
   "Type5": "ex64_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Bola",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "nonlethal, trip",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex65_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Bola, Brutal",
   "Cost": "15 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "2 lbs.",
   "Type2": "B and P",
   "Special": "trip",
   "Source": "PCS:ISWG-Revised",
   "Type": "ex_",
   "Type5": "ex66_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Boomerang",
   "Cost": "3 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "30 ft.",
   "Weight1": "3 lbs.",
   "Type2": "B",
   "Special": "-",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex67_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Bow, thorn",
   "Cost": "50 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x3",
   "Range": "40 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex68_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, crank (heavy)",
   "Cost": "400 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "120 ft.",
   "Weight1": "12 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PPC:RTT",
   "Type": "ex_",
   "Type5": "ex69_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, crank (light)",
   "Cost": "250 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "80 ft.",
   "Weight1": "6 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PPC:RTT",
   "Type": "ex_",
   "Type5": "ex70_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, double",
   "Cost": "300 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "80 ft.",
   "Weight1": "18 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex71_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, hand",
   "Cost": "100 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "30 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex72_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, launching",
   "Cost": "75 gp",
   "Dmg_(S)": "-",
   "Dmg_(M)": "-",
   "Critical": "-",
   "Range": "30 ft.",
   "Weight1": "8 lbs.",
   "Type2": "-",
   "Special": "see text",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex73_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, repeating heavy",
   "Cost": "400 gp",
   "Dmg_(S)": "1d8",
   "Dmg_(M)": "1d10",
   "Critical": "19-20/x2",
   "Range": "120 ft.",
   "Weight1": "12 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex74_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Crossbow, repeating",
   "Cost": "250 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "19-20/x2",
   "Range": "80 ft.",
   "Weight1": "6 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex75_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Flask Thrower",
   "Cost": "25 gp",
   "Dmg_(S)": "-",
   "Dmg_(M)": "-",
   "Critical": "-",
   "Range": "20 ft.",
   "Weight1": "4 lbs.",
   "Type2": "-",
   "Special": "see text",
   "Source": "PPC:Goblins",
   "Type": "ex_",
   "Type5": "ex76_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Grappling hook",
   "Cost": "6 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "14 lbs.",
   "Type2": "P",
   "Special": "grapple",
   "Source": "PPC:Pirates",
   "Type": "ex_",
   "Type5": "ex77_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Lasso",
   "Cost": "1 sp",
   "Dmg_(S)": "-",
   "Dmg_(M)": "-",
   "Critical": "-",
   "Range": "-",
   "Weight1": "5 lbs.",
   "Type2": "-",
   "Special": "see text",
   "Source": "PRG:APG",
   "Type": "ex_",
   "Type5": "ex78_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Net",
   "Cost": "20 gp",
   "Dmg_(S)": "-",
   "Dmg_(M)": "-",
   "Critical": "-",
   "Range": "10 ft.",
   "Weight1": "6 lbs.",
   "Type2": "-",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex79_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Net, snag",
   "Cost": "30 gp",
   "Dmg_(S)": "see text",
   "Dmg_(M)": "see text",
   "Critical": "-",
   "Range": "10 ft.",
   "Weight1": "10 lbs.",
   "Type2": "P",
   "Special": "trip, see text",
   "Source": "PRG:ARG",
   "Type": "ex_",
   "Type5": "ex80_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Shield, throwing",
   "Cost": "+50 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "20 ft.",
   "Weight1": "-",
   "Type2": "B",
   "Special": "performance, trip",
   "Source": "PRG:UC",
   "Type": "ex_",
   "Type5": "ex81_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Shrillshaft javelin",
   "Cost": "35 gp",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "30 ft.",
   "Weight1": "3 lbs.",
   "Type2": "P",
   "Special": "see text",
   "Source": "PPC:Goblins",
   "Type": "ex_",
   "Type5": "ex82_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Shuriken (5)",
   "Cost": "1 gp",
   "Dmg_(S)": "1",
   "Dmg_(M)": "1d2",
   "Critical": "x2",
   "Range": "10 ft.",
   "Weight1": "1/2 lbs.",
   "Type2": "P",
   "Special": "monk",
   "Source": "CRB",
   "Type": "ex_",
   "Type5": "ex83_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Sling, double",
   "Cost": "10 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "50 ft.",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "double, see text",
   "Source": "PPC:Halflings",
   "Type": "ex_",
   "Type5": "ex84_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Sling glove",
   "Cost": "5 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "x2",
   "Range": "50 ft.",
   "Weight1": "2 lbs.",
   "Type2": "B",
   "Special": "-",
   "Source": "PPC:AA",
   "Type": "ex_",
   "Type5": "ex85_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Sling staff, halfling",
   "Cost": "20 gp",
   "Dmg_(S)": "1d6",
   "Dmg_(M)": "1d8",
   "Critical": "x3",
   "Range": "80 ft.",
   "Weight1": "3 lbs.",
   "Type2": "B",
   "Special": "-",
   "Source": "PRG:CRB",
   "Type": "ex_",
   "Type5": "ex86_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Sling, stitched",
   "Cost": "-",
   "Dmg_(S)": "1d4",
   "Dmg_(M)": "1d6",
   "Critical": "x2",
   "Range": "-",
   "Weight1": "1 lb.",
   "Type2": "B",
   "Special": "disarm, trip",
   "Source": "PPC:Halflings",
   "Type": "ex_",
   "Type5": "ex87_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Wrist launcher",
   "Cost": "200 gp",
   "Dmg_(S)": "-",
   "Dmg_(M)": "-",
   "Critical": "-",
   "Range": "20 ft.",
   "Weight1": "1 lb.",
   "Type2": "P",
   "Special": "-",
   "Source": "PRG:UI",
   "Type": "ex_",
   "Type5": "ex88_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Wrist launcher, heavy",
   "Cost": "250 gp",
   "Dmg_(S)": "1d3",
   "Dmg_(M)": "1d4",
   "Critical": "19-20/x2",
   "Range": "30 ft.",
   "Weight1": "2 lbs.",
   "Type2": "P",
   "Special": "-",
   "Source": "PRG:UI",
   "Type": "ex_",
   "Type5": "ex89_",
   "Type3": "two_handed",
   "Type4": "ranged"
 },
 {
   "Label": "Claw",
   "Cost": "",
   "Dmg_S": "",
   "Dmg_M": "1d4",
   "Critical": "x2",
   "Range": "",
   "Weight1": "",
   "Type2": "S",
   "Special": "",
   "Source": "",
   "Type": "",
   "Type3": "",
   "Type4": ""
 }
];
var weapon_list_names = ["Throwing arrow cord","Spear-sling","Shortbow, composite","Shortbow","Pilum","Longbow, composite (+5)","Longbow, composite (+4)","Longbow, composite (+3)","Longbow, composite (+2)","Longbow, composite (+1)","Longbow, composite (+0)","Longbow","Hurlbat","Hunga munga","Dart, jolting","Chakram","Ammentum","Spear, syringe","Scythe","Ranseur","Planson","Pickaxe","Ogre hook","Lance","Horsechopper","Hammer, lucerne","Halberd","Guisarme","Greatsword","Greatclub","Greataxe","Glaive-guisarme","Glaive","Flail, heavy","Falchion","Earth breaker","Bill","Bec de corbin","Bardiche","Warhammer","Trident","Terbutje, steel","Terbutje","Sword cane","Spiked shield, heavy","Shield, heavy","Scizore","Scimitar","Scabbard, combat (sharpened)","Rapier","Pick, heavy","Manople","Longsword","Klar","Gandasa","Flail","Cutlass","Combat scabbard","Battleaxe","Ankus","War razor","Sword, short","Starknife","Spiked shield, light","Spiked armor","Shield, light","Sea-knife","Sap","Ratfolk tailblade","Pick, light","Machete","Kukri","Kobold tail attachment, Sweeper","Kobold tail attachment, Spiked","Kobold tail attachment, Razored","Kobold tail attachment, Pounder","Kobold tail attachment, Long lash","Knife, switchblade","Handaxe","Gladius","Hammer, light","Dogslicer","Blade boot","Axe, throwing","Axe, boarding","Stonebow","Stingchuck","Sling","Javelin","Dart","Crossbow, light (underwater)","Crossbow, light","Crossbow, heavy (underwater)","Crossbow, heavy","Blowgun","Spear, weighted","Spear, boar","Spear","Quarterstaff","Longspear","Kumade, collapsible","Kumade","Boarding pike","Bayonet","Shortspear","Morningstar","Mace, heavy","Club, mere","Club","Wooden stake","Spring blade","Sickle","Mace, light","Kunai","Hook hand","Gauntlet, spiked","Dagger, punching","Dagger","Cestus","Brass knuckles","Brass knife","Battle aspergillum","Unarmed strike","Gauntlet"];